# Generated by Django 4.0.5 on 2022-06-25 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=250)),
                ('LikeCount', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCount', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=250)),
                ('LikeCount', models.IntegerField(default=0, null=True)),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('Art', models.ImageField(upload_to='media')),
                ('Comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poste', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.poste')),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
