# Generated by Django 4.0.5 on 2022-06-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
