# Generated by Django 4.0.5 on 2022-06-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Comment',
        ),
    ]
