# Generated by Django 4.0.5 on 2022-06-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0004_remove_likedposts_user_likedposts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedposts',
            name='Poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artapp.poste'),
        ),
    ]
