# Generated by Django 4.0.5 on 2022-06-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0005_alter_likedposts_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedposts',
            name='Poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.poste'),
        ),
        migrations.AlterField(
            model_name='likedposts',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Artapp.profile'),
        ),
    ]
