# Generated by Django 4.0.5 on 2022-06-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0006_alter_likedposts_poste_alter_likedposts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedposts',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artapp.profile'),
        ),
    ]
